# Generated by Django 3.0.6 on 2020-05-20 14:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(default=None, max_length=100)),
                ('order_no', models.CharField(default=None, max_length=10)),
                ('act_date', models.DateTimeField(auto_now_add=True)),
                ('supreme_commissioner', models.CharField(default=None, max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('commissioner2', models.CharField(default=None, max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('commissioner3', models.CharField(default=None, max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('commissioner4', models.CharField(default=None, max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('location', models.CharField(default=None, max_length=100)),
                ('seller_company_title', models.CharField(default=None, max_length=100)),
                ('serial_id', models.CharField(default=None, max_length=10)),
                ('serial_no', models.CharField(default=None, max_length=10)),
                ('responsible_worker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('unit', models.CharField(default=None, max_length=100)),
                ('amount', models.IntegerField()),
                ('cost', models.FloatField()),
                ('total_sum', models.FloatField()),
                ('purpose', models.CharField(default=None, max_length=100, null=True)),
                ('form', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
            ],
        ),
    ]
